### ISSUE TITLE
Modifications de la fenêtre associée au bouton "Unfold hierarchy"

### ISSUE THREAD

**Issue by carinehue** [khiopsrelease/kc-release#11]
**Premier pavé :**
- remplacer "Information" par "Information rate"
- pour la valeur de ce taux d'information, donner un seul chiffre significatif après la virgule
Exemple pour Adult2vars 99.6015 -> 99.6; 96.1998 -> 96.2
- ajouter un logo "Warning" à côté de la valeur du taux quand elle vaut 0 (comme dans l'ancien outil, pour alerter l'utilisateur
car dans ce cas la hauteur de la barre du graphique ne sera plus visible car réduite à 0)

**Graphique 1** 
- Titre : modifier le titre en "Information rate"
- Axe des ordonnées : donner plus de détail avec une graduation de 0 à 100 par pas de 20
- Barre : modifier la hauteur de la barre noire que l'on déplace pour qu'elle soit égale au taux d'information 
(actuellement elle monte toujours à 100)
- Infobulle : ajout d'une infobulle identique à celle de l'ancien outil quand on déplace la souris sur le graphique
 "The evolution of the information according to the number of clusters : ..... hierarchy"

**Graphique 2 :**
- Axe des ordonnées : est il possible de le détailler un peu plus (au moins 5 graduations) ?
- Légende de l'axe des ordonnées : remplacer "Information" par "Nb of clusters per dimension"
- Barre : modifier la hauteur de la barre que l'on déplace pour qu'elle soit égale au maximum des nombres de cluster par 
dimension
- Infobulle : ajout de l'infobulle "Click on dimension to highlight data" quand on passe la souris sur la légende des dimensions
- Interaction : reprendre l'interaction de l'ancien outil qui consiste à mettre en gras la courbe associée à la dimension sur laquelle on clique au niveau de la légende des couleurs

**Comment by stephanebouget** [comment]
@carinehue je n'arrive pas à trouver la logique pour déterminer la hauteur de la barre que l'on déplace pour qu'elle soit égale au maximum des nombres de cluster par dimension ? 
![image](https://user-images.githubusercontent.com/13203455/158787056-4b3c0967-ac68-4403-a8e9-8b1905d72dea.png)

**Comment by carinehue** [comment]
La hauteur est donnée par le maximum des valeurs de la colonne 'numberOfClusters' du tableau du bas.
