### ISSUE TITLE
Sauvegarde du json d'un repliement via Unfold hierarchy : ordre des "values" dans un cluster, ordre des "clusters" dans "dimensionHierarchies"

### ISSUE THREAD

**Issue by carinehue** [khiopsrelease/kc-release#17]
Une fois que l'on a replié un coclustering via la fonctionnalité Unfold hierarchy, on peut sauvegarder ce repliement avec "Save current hierarchy as". Les clusters repliés sont sauvegardés à l'état de feuilles, cela élague le coclustering.

Les valeurs d'un cluster replié sont à décrire dans un certain ordre.
Dans le fichier json du coclustering initial, les "values" sont ordonnées par effectif décroissant (champ "valueFrequencies").
Exemple :  Adult avec variables occupation et education
Extrait du fichier json initial avant repliement. La liste des "valueGroups" est dans un certain ordre. Les deux premiers sont "cluster": "{Prof-specialty, Armed-Forces}" puis "cluster": "{Exec-managerial}".
Dans le cluster "cluster": "{Prof-specialty, Armed-Forces}", la value "Prof-speciality" est avant "Armed-forces" car son effectif 5787 est supérieur à 13.

		"dimensionPartitions": [
			{
				"name": "occupation",
				"type": "Categorical",
				"valueGroups": [
					{
						"cluster": "{Prof-specialty, Armed-Forces}",
						"values": ["Prof-specialty","Armed-Forces"],
						"valueFrequencies": [5787,13],
						"valueTypicalities": [1,0.00278259]
					},
					{
						"cluster": "{Exec-managerial}",
						"values": ["Exec-managerial"],
						"valueFrequencies": [3973],
						"valueTypicalities": [1]
					},

Dans le fichier json du coclustering replié, si l'on regarde le cluster replié à partir de ces deux clusters, il faudrait que cet ordre soit maintenu c'est à dire que l'on obtienne 
   "dimensionPartitions": [
      {
        "name": "occupation",
        "type": "Categorical",
        "valueGroups": [
          {
            "cluster": "A7",
            "values": [
              "Prof-specialty",
              "Armed-Forces",
              "Exec-managerial"
            ],
            "valueFrequencies": [
              5787,
              13,
              3973
            ],
            "valueTypicalities": [
              1,
              0.00278259,
              1
            ]
          },
On retrouve  en premier les "values" du 1er cluster de la liste : Prof-specialty puis Armed-Forces (dans le même ordre que l'ordre du json initial) ; puis la modalité du second cluster "Exec-managerial".

Actuellement l'ordre du json que KhiopsCovizu produit est différent car "Exec-managerial" apparait en premier.

   "dimensionPartitions": [
      {
        "name": "occupation",
        "type": "Categorical",
        "valueGroups": [
          {
            "cluster": "A7",
            "values": [
              "Exec-managerial",
              "Prof-specialty",
              "Armed-Forces"
            ],
            "valueFrequencies": [
              3973,
              5787,
              13
            ],
            "valueTypicalities": [
              1,
              1,
              0.00278259
            ]
          },

Pour ce qui est de l'ordre des clusters dans le champ ""dimensionHierarchies", l'ordre attendu est le suivant :
- on liste d'abord tous les clusters qui ont le statut de feuille et on les met dans l'ordre de leur champ "rank" 
-  on liste ensuite tous les clusters qui ne sont pas des feuilles et on les met à nouveau dans l'ordre de leur champ "rank"

Ordre attendu pour les clusters de la variable "occupation" : {2,8,14} pour les feuilles puis {4,12} pour les autres
Ordre actuel dans le fichier json produit par KhiopsCV : {2,4,8,12,14}

[AdultEducationOccupation-3-2-JsonActuel-JsonCible.zip](https://github.com/khiopsrelease/kc-release/files/8488088/AdultEducationOccupation-3-2-JsonActuel-JsonCible.zip)

**Comment by stephanebouget** [comment]
@carinehue tu aurais le fichier original sans nœuds pliés pour que je puisse comparer ? merci

**Comment by carinehue** [comment]
Oui le voici
[CoclusteringAdultEducationSansRepliement.zip](https://github.com/khiopsrelease/kc-release/files/8521462/CoclusteringAdultEducationSansRepliement.zip)

**Comment by khiopsrelease** [comment]
le defaultGroupIndex ne se met pas non plus à jour
