### ISSUE TITLE
Save current hierarchy as : champ "cells" et "cellPartIndexes"

### ISSUE THREAD

**Issue by carinehue** [khiopsrelease/kc-release#22]
Suite à un repliement, au niveau du rapport json, deux corrections à apporter : 
- le champ "cells" dans "summary" doit contenir le nombre de cellules non vide, qui peut être inférieur au nombre de cellules théorique. Il est obtenu en comptant le nombre d'éléments dans la liste "cellPartIndexes" ou dans "cellFrequencies"
- dans la liste "cellPartIndexes", les index décrits par des champs "0", "1", "2" sont à remplacer par des valeurs entières 0,1,2 (sinon les fichiers ne sont plus utilisables par Khiops )

Ci-joint un exemple de coclustering initial sur la base Iris avec 3 variables : Petal Length, Petal Width et Class en Context.
Le repliement effectué est repliement obtenu en utilisant "UnfoldHierarchy" et en passant de 9 clusters à 8 clusters.
On obtient le rapport json Coclustering-Rep8 alors que l'on devrait obtenir Coclustering-Rep8-Cible.

[IrisRepliement8Clusters.zip](https://github.com/khiopsrelease/kc-release/files/8870775/IrisRepliement8Clusters.zip)

**Comment by stephanebouget** [comment]
Hello @carinehue 
dans ton exemple "cible", le dimensionHierarchies de la première variable PetalLength est ordonné par rank sans prendre en compte isLeaf :
![image](https://user-images.githubusercontent.com/13203455/173321472-0a0827ca-ef4e-4f46-99bd-8ccc2a6561d5.png)

c'est contradictoire avec #23 
c'est une erreur ou y a t'il une subtilité ?

**Comment by carinehue** [comment]
Salut @stephanebouget 
C'est une erreur dans mon exemple cible pour cette issue, je n'avais pas encore identifié ce souci d'ordre : le cluster ]2.4; + inf[ devrait apparaître avant le cluster ]-inf; + inf[  (et après le cluster ]-inf; 2.4[).

**Comment by stephanebouget** [comment]
ok
