### ISSUE TITLE
Import external data with tabulated or multi-lines data

### ISSUE THREAD

**Issue by carinehue** [khiopsrelease/kc-release#24]
The "external data" functionality doesn't work when text field includes tab or new lines.
For the external data given in the zip, the new version of KCV differs from the old version for "Some-college" external text (only the text of the first line) and "Masters" text (no tab)
[ExternalData.zip](https://github.com/khiopsrelease/kc-release/files/9037619/ExternalData.zip)

The description of the format used for external data files is described here : 
The external data files are tab-separated value files. The text type has a special format. This format allows you to display multiple lines in a text field for an item.
All characters are allowed, however three characters have a special role:
•	The field separator : “\t” (tab)
•	The new line character : “\n” (eol)
•	The beginning or end of field indicator : «"» (double-quote)
If a field contains the tab character and/or the new line character, this field must be surrounded by two double-quotes «"». If a field contains the double-quote character, this character must be doubled.

**Comment by stephanebouget** [comment]
@carinehue Peux-tu me rappeler comment fonctionne l'import external data ?
je fais import new file> et ensuite ?
que dois-je mettre dans join key et Dimension ?
(je n'arrive pas à afficher quoi que ce soit ...)

**Comment by carinehue** [comment]
Import new file : tu choisis ExternalDataEducation.txt
Join key et Dimension = education 
cocher Import
Load data puis fermer la fenêtre en haut à droite
![ImportFile](https://user-images.githubusercontent.com/101398951/177316405-c41377fc-16af-4b04-aa9d-ac25790ca2ec.JPG)

Activer la view des External data 
Sélectionner l'un des clusters d'education pour lesquels on a des donnés externes dans le fichier   : Bachelors, HS-grad, Masters,  Some-college, et 11th
