### ISSUE TITLE
Wrong interval values into statistics components.

### ISSUE THREAD

**Issue by stephanebouget** [khiopsrelease/kc-release#42]
quand on visualise les « statistics », on voit en toutes lettre -inf ou plus inf, au lieu des valeurs correspondantes.
![image](https://user-images.githubusercontent.com/13203455/192722980-133a6491-0826-432d-b5ce-8dedcdfc5a94.png)

**Comment by carinehue** [comment]
pas certaine que cela soit à modifier : c'est bien ce que l'on avait dans l'ancien outil également
![StatisticInf](https://user-images.githubusercontent.com/101398951/192731254-e4d18fac-4be7-4c05-98fa-ddcbbe38759a.JPG)

**Comment by stephanebouget** [comment]
@carinehue c'est Marc qui m'a demandé de changer. Je fais quoi ?

**Comment by carinehue** [comment]
Je viens d'échanger avec lui sur les deux points qu'il t'a remontés :  ok pour résoudre le point sur le "Undefined" qui apparait pour une des variables. Par contre, pour l'instant on ne modifie pas cet affichage ]-inf, + inf[.
