### ISSUE TITLE
Installer blurry in High DPI screens

### ISSUE THREAD

**Issue by folmos-at-orange** [khiopsrelease/kc-release#66]
In Windows, the installer of the khiops viz and khiops coviz apps is blurry in hiDPI screens (see photo below).

If by chance you are using electron-builder to create this installer, the fix is to add a line to the `build/installer.nsh` file: https://github.com/electron-userland/electron-builder/issues/5329#issuecomment-710654927

<img src="https://github.com/khiopsrelease/kc-release/assets/92923444/bcf1b034-ca16-4bfa-92f9-d61c08eae185" width = 623/>

**Comment by stephanebouget** [comment]
à rechecker car je n'ai pas d'écran hidpi pour tester
